create table tb_clients (client_id bigserial not null, cpf varchar(11) not null, address varchar(255), email varchar(255), name varchar(255), primary key (client_id));
create table tb_products (moment date, price float(53), client_id bigint, id bigserial not null, description varchar(255), name varchar(255), primary key (id));
alter table if exists tb_products add constraint FKnyv06k3rglsds8wr7s4wy939l foreign key (client_id) references tb_clients;
create table tb_clients (client_id bigserial not null, cpf varchar(11) not null, address varchar(255), email varchar(255), name varchar(255), primary key (client_id));
create table tb_products (moment date, price float(53), client_id bigint, id bigserial not null, description varchar(255), name varchar(255), primary key (id));
alter table if exists tb_products add constraint FKnyv06k3rglsds8wr7s4wy939l foreign key (client_id) references tb_clients;
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Maria Suelen', 'maria@gmail.com', '12345678900', 'Rua das Chatas');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('João Vitor', 'joao@gmail.com', '45678990012', 'Avenida Fliper Ama');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Maria Oliveira', 'maria@gmail.com', '12345678901', 'Rua dos Girassóis, 123');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Pedro Santos', 'pedro@hotmail.com', '98765432109', 'Avenida Principal, 456');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Ana Silva', 'ana@yahoo.com', '23456789012', 'Travessa das Rosas, 789');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Carlos Pereira', 'carlos@gmail.com', '34567890123', 'Praça das Árvores, 101');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Mariana Costa', 'mariana@hotmail.com', '87654321098', 'Alameda das Flores, 567');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Rafael Oliveira', 'rafael@yahoo.com', '56789012345', 'Rua da Esperança, 321');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Juliana Santos', 'juliana@gmail.com', '67890123456', 'Avenida dos Sonhos, 543');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Gustavo Silva', 'gustavo@hotmail.com', '78901234567', 'Travessa das Estrelas, 876');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Fernanda Pereira', 'fernanda@yahoo.com', '89012345678', 'Praça das Maravilhas, 234');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Lucas Costa', 'lucas@gmail.com', '90123456789', 'Alameda dos Desejos, 987');
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Calça Jeans', 'lorem ipsum dolor', 139.99, '2024-01-15', 1);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Camisa Polo Preta', 'lorem ipsum dolor', 49.99, '2024-01-18', 2);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Camiseta Branca', 'lorem ipsum dolor', 29.99, '2024-01-15', 4);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Vestido Floral', 'lorem ipsum dolor', 89.99, '2024-01-15', 3);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Sapato Social', 'lorem ipsum dolor', 79.99, '2024-01-15', 4);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Jaqueta de Couro', 'lorem ipsum dolor', 149.99, '2024-01-15', 5);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Bermuda Jeans', 'lorem ipsum dolor', 49.99, '2024-01-15', 6);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Blusa de Tricô', 'lorem ipsum dolor', 69.99, '2024-01-15', 7);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Tênis Esportivo', 'lorem ipsum dolor', 59.99, '2024-01-15', 8);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Moletom Cinza', 'lorem ipsum dolor', 79.99, '2024-01-15', 9);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Chapéu de Palha', 'lorem ipsum dolor', 19.99, '2024-01-15', 10);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Pijama Listrado', 'lorem ipsum dolor', 39.99, '2024-01-15', 1);
create table tb_clients (client_id bigserial not null, cpf varchar(11) not null, address varchar(255), email varchar(255), name varchar(255), primary key (client_id));
create table tb_products (moment date, price float(53), client_id bigint, id bigserial not null, description varchar(255), name varchar(255), primary key (id));
alter table if exists tb_products add constraint FKnyv06k3rglsds8wr7s4wy939l foreign key (client_id) references tb_clients;
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Maria Suelen', 'maria@gmail.com', '12345678900', 'Rua das Chatas');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('João Vitor', 'joao@gmail.com', '45678990012', 'Avenida Fliper Ama');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Maria Oliveira', 'maria@gmail.com', '12345678901', 'Rua dos Girassóis, 123');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Pedro Santos', 'pedro@hotmail.com', '98765432109', 'Avenida Principal, 456');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Ana Silva', 'ana@yahoo.com', '23456789012', 'Travessa das Rosas, 789');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Carlos Pereira', 'carlos@gmail.com', '34567890123', 'Praça das Árvores, 101');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Mariana Costa', 'mariana@hotmail.com', '87654321098', 'Alameda das Flores, 567');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Rafael Oliveira', 'rafael@yahoo.com', '56789012345', 'Rua da Esperança, 321');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Juliana Santos', 'juliana@gmail.com', '67890123456', 'Avenida dos Sonhos, 543');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Gustavo Silva', 'gustavo@hotmail.com', '78901234567', 'Travessa das Estrelas, 876');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Fernanda Pereira', 'fernanda@yahoo.com', '89012345678', 'Praça das Maravilhas, 234');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Lucas Costa', 'lucas@gmail.com', '90123456789', 'Alameda dos Desejos, 987');
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Calça Jeans', 'lorem ipsum dolor', 139.99, '2024-01-15', 1);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Camisa Polo Preta', 'lorem ipsum dolor', 49.99, '2024-01-18', 2);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Camiseta Branca', 'lorem ipsum dolor', 29.99, '2024-01-15', 4);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Vestido Floral', 'lorem ipsum dolor', 89.99, '2024-01-15', 3);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Sapato Social', 'lorem ipsum dolor', 79.99, '2024-01-15', 4);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Jaqueta de Couro', 'lorem ipsum dolor', 149.99, '2024-01-15', 5);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Bermuda Jeans', 'lorem ipsum dolor', 49.99, '2024-01-15', 6);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Blusa de Tricô', 'lorem ipsum dolor', 69.99, '2024-01-15', 7);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Tênis Esportivo', 'lorem ipsum dolor', 59.99, '2024-01-15', 8);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Moletom Cinza', 'lorem ipsum dolor', 79.99, '2024-01-15', 9);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Chapéu de Palha', 'lorem ipsum dolor', 19.99, '2024-01-15', 10);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Pijama Listrado', 'lorem ipsum dolor', 39.99, '2024-01-15', 1);
create table tb_clients (client_id bigserial not null, cpf varchar(11) not null, address varchar(255), email varchar(255), name varchar(255), primary key (client_id));
create table tb_products (moment date, price float(53), client_id bigint, id bigserial not null, description varchar(255), name varchar(255), primary key (id));
alter table if exists tb_products add constraint FKnyv06k3rglsds8wr7s4wy939l foreign key (client_id) references tb_clients;
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Maria Suelen', 'maria@gmail.com', '12345678900', 'Rua das Chatas');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('João Vitor', 'joao@gmail.com', '45678990012', 'Avenida Fliper Ama');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Maria Oliveira', 'maria@gmail.com', '12345678901', 'Rua dos Girassóis, 123');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Pedro Santos', 'pedro@hotmail.com', '98765432109', 'Avenida Principal, 456');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Ana Silva', 'ana@yahoo.com', '23456789012', 'Travessa das Rosas, 789');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Carlos Pereira', 'carlos@gmail.com', '34567890123', 'Praça das Árvores, 101');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Mariana Costa', 'mariana@hotmail.com', '87654321098', 'Alameda das Flores, 567');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Rafael Oliveira', 'rafael@yahoo.com', '56789012345', 'Rua da Esperança, 321');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Juliana Santos', 'juliana@gmail.com', '67890123456', 'Avenida dos Sonhos, 543');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Gustavo Silva', 'gustavo@hotmail.com', '78901234567', 'Travessa das Estrelas, 876');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Fernanda Pereira', 'fernanda@yahoo.com', '89012345678', 'Praça das Maravilhas, 234');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Lucas Costa', 'lucas@gmail.com', '90123456789', 'Alameda dos Desejos, 987');
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Calça Jeans', 'lorem ipsum dolor', 139.99, '2024-01-15', 1);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Camisa Polo Preta', 'lorem ipsum dolor', 49.99, '2024-01-18', 2);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Camiseta Branca', 'lorem ipsum dolor', 29.99, '2024-01-15', 4);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Vestido Floral', 'lorem ipsum dolor', 89.99, '2024-01-15', 3);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Sapato Social', 'lorem ipsum dolor', 79.99, '2024-01-15', 4);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Jaqueta de Couro', 'lorem ipsum dolor', 149.99, '2024-01-15', 5);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Bermuda Jeans', 'lorem ipsum dolor', 49.99, '2024-01-15', 6);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Blusa de Tricô', 'lorem ipsum dolor', 69.99, '2024-01-15', 7);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Tênis Esportivo', 'lorem ipsum dolor', 59.99, '2024-01-15', 8);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Moletom Cinza', 'lorem ipsum dolor', 79.99, '2024-01-15', 9);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Chapéu de Palha', 'lorem ipsum dolor', 19.99, '2024-01-15', 10);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Pijama Listrado', 'lorem ipsum dolor', 39.99, '2024-01-15', 1);
create table tb_clients (client_id bigserial not null, cpf varchar(11) not null, address varchar(255), email varchar(255), name varchar(255), primary key (client_id));
create table tb_products (moment date, price float(53), client_id bigint, id bigserial not null, description varchar(255), name varchar(255), primary key (id));
alter table if exists tb_products add constraint FKnyv06k3rglsds8wr7s4wy939l foreign key (client_id) references tb_clients;
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Maria Suelen', 'maria@gmail.com', '12345678900', 'Rua das Chatas');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('João Vitor', 'joao@gmail.com', '45678990012', 'Avenida Fliper Ama');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Maria Oliveira', 'maria@gmail.com', '12345678901', 'Rua dos Girassóis, 123');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Pedro Santos', 'pedro@hotmail.com', '98765432109', 'Avenida Principal, 456');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Ana Silva', 'ana@yahoo.com', '23456789012', 'Travessa das Rosas, 789');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Carlos Pereira', 'carlos@gmail.com', '34567890123', 'Praça das Árvores, 101');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Mariana Costa', 'mariana@hotmail.com', '87654321098', 'Alameda das Flores, 567');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Rafael Oliveira', 'rafael@yahoo.com', '56789012345', 'Rua da Esperança, 321');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Juliana Santos', 'juliana@gmail.com', '67890123456', 'Avenida dos Sonhos, 543');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Gustavo Silva', 'gustavo@hotmail.com', '78901234567', 'Travessa das Estrelas, 876');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Fernanda Pereira', 'fernanda@yahoo.com', '89012345678', 'Praça das Maravilhas, 234');
INSERT INTO tb_clients(name, email, cpf, address) VALUES ('Lucas Costa', 'lucas@gmail.com', '90123456789', 'Alameda dos Desejos, 987');
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Calça Jeans', 'lorem ipsum dolor', 139.99, '2024-01-15', 1);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Camisa Polo Preta', 'lorem ipsum dolor', 49.99, '2024-01-18', 2);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Camiseta Branca', 'lorem ipsum dolor', 29.99, '2024-01-15', 4);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Vestido Floral', 'lorem ipsum dolor', 89.99, '2024-01-15', 3);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Sapato Social', 'lorem ipsum dolor', 79.99, '2024-01-15', 4);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Jaqueta de Couro', 'lorem ipsum dolor', 149.99, '2024-01-15', 5);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Bermuda Jeans', 'lorem ipsum dolor', 49.99, '2024-01-15', 6);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Blusa de Tricô', 'lorem ipsum dolor', 69.99, '2024-01-15', 7);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Tênis Esportivo', 'lorem ipsum dolor', 59.99, '2024-01-15', 8);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Moletom Cinza', 'lorem ipsum dolor', 79.99, '2024-01-15', 9);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Chapéu de Palha', 'lorem ipsum dolor', 19.99, '2024-01-15', 10);
INSERT INTO tb_products (name, description, price, moment, client_id) VALUES ('Pijama Listrado', 'lorem ipsum dolor', 39.99, '2024-01-15', 1);
